apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "envoy.name" . }}
  labels:
    app: {{ template "envoy.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  envoy.yaml: |-
    admin:
      access_log_path: "/dev/null"
      address:
        socket_address:
          address: 0.0.0.0
          port_value: {{ .Values.envoy.ports.admin.containerPort }}
    static_resources:
      listeners:
      - name: redis_listener
        address:
          socket_address:
            address: 0.0.0.0
            port_value: {{ .Values.envoy.ports.redis.containerPort }}
        filter_chains:
        - filters:
          - name: envoy.filters.network.redis_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProxy
              stat_prefix: redis_stats
              prefix_routes:
                catch_all_route:
                  cluster: redis_cluster
              settings:
                op_timeout: 5s
                dns_cache_config:
                  name: envoy.dns_cache.redis_cache
                  dns_lookup_family: V4_ONLY
                enable_redirection: true
                enable_command_stats: true
              {{- if .Values.usePassword }}
              downstream_auth_passwords:
                - environment_variable: REDIS_PASSWORD
              {{- end }}
      clusters:
      - name: redis_cluster
        connect_timeout: 0.25s
        lb_policy: MAGLEV
        dns_lookup_family: V4_ONLY
        load_assignment:
          cluster_name: redis_cluster
          endpoints:
          - lb_endpoints:
        {{- $count := .Values.cluster.nodes | int }}
        {{- $redisPort := .Values.redis.containerPorts.redis -}}
        {{- range $i, $e := until $count }}
            - endpoint:
                address:
                  socket_address:
                    address: {{ include "common.names.fullname" $ }}-{{ $i }}.{{ template "common.names.fullname" $ }}-headless
                    port_value: {{ $redisPort }}
        {{- end }}
        typed_extension_protocol_options:
          envoy.filters.network.redis_proxy:
            "@type": type.googleapis.com/google.protobuf.Struct
            value:
            {{- if .Values.usePassword }}
              auth_password:
                environment_variable: REDIS_PASSWORD
            {{- end }}
        cluster_type:
          name: envoy.clusters.redis
          typed_config:
            "@type": type.googleapis.com/google.protobuf.Struct
            value:
              cluster_refresh_rate: 5s
              cluster_refresh_timeout: 3s
              redirect_refresh_interval: 5s
              redirect_refresh_threshold: 5
        health_checks:
          custom_health_check:
            name: envoy.health_checkers.redis
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.health_checkers.redis.v3.Redis
          timeout: 1s
          interval: 5s
          unhealthy_threshold: 3
          healthy_threshold: 1
