apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "envoy.name" . }}
  labels:
    app: {{ template "envoy.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "envoy.name" . }}
      release: {{ .Release.Name }}
{{ .Values.envoy.podDisruptionBudget | indent 2 }}
